wandb_version: 1

method:
  desc: null
  value: random
metric:
  desc: null
  value:
    name: mean_mean_reward
    goal: maximize
parameters:
  desc: null
  value:
    learning_rate:
      min: 3.0e-05
      max: 0.003
    gamma:
      min: 0.9
      max: 0.9999
    batch_size:
      min: 32
      max: 128
    n_epochs:
      min: 5
      max: 20
    gae_lambda:
      min: 0.85
      max: 0.999
_wandb:
  desc: null
  value:
    python_version: 3.8.20
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1749834781.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.8.20
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 37
gae_lambda:
  desc: null
  value: 0.952580315410426
gamma:
  desc: null
  value: 0.9936548368071472
learning_rate:
  desc: null
  value: 0.00248632704015726
n_epochs:
  desc: null
  value: 18
