wandb_version: 1

policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 100000
env_id_source:
  desc: null
  value: CustomHopper-source-v0
env_id_target:
  desc: null
  value: CustomHopper-target-v0
test_episodes:
  desc: null
  value: 50
success_threshold:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.8.20
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1749939743.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 17
      - 23
      - 35
      - 37
      4: 3.8.20
      5: 0.16.6
      8:
      - 5
      10:
      - 3
      13: linux-x86_64
