wandb_version: 1

policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 400000
env_id:
  desc: null
  value: CustomHopper-source-v0
_wandb:
  desc: null
  value:
    python_version: 3.8.20
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1749933868.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 3
      - 16
      - 22
      - 23
      - 35
      4: 3.8.20
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
device:
  desc: null
  value: cuda
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x733b4694be50>
_vec_normalize_env:
  desc: null
  value: None
verbose:
  desc: null
  value: 2
policy_kwargs:
  desc: null
  value: '{}'
observation_space:
  desc: null
  value: Box([-inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf], [inf inf inf
    inf inf inf inf inf inf inf inf], (11,), float64)
action_space:
  desc: null
  value: Box([-1. -1. -1.], [1. 1. 1.], (3,), float32)
n_envs:
  desc: null
  value: 1
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 400000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: 42
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1749935134615318585
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (pi_features_extractor): FlattenExtractor(\n\
    \    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (vf_features_extractor):\
    \ FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor):\
    \ MlpExtractor(\n    (shared_net): Sequential()\n    (policy_net): Sequential(\n\
    \      (0): Linear(in_features=11, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n    (value_net): Sequential(\n      (0): Linear(in_features=11, out_features=64,\
    \ bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64, out_features=64,\
    \ bias=True)\n      (3): Tanh()\n    )\n  )\n  (action_net): Linear(in_features=64,\
    \ out_features=3, bias=True)\n  (value_net): Linear(in_features=64, out_features=1,\
    \ bias=True)\n)"
learning_rate:
  desc: null
  value: 0.0012541462101916157
tensorboard_log:
  desc: null
  value: runs/6xeqoywz
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x733b4699ee50>
_last_obs:
  desc: null
  value: "[[ 1.24984339e+00  4.20770821e-03 -1.80545207e-04  5.60941601e-04\n   1.84226466e-03\
    \ -3.59075061e-03 -1.20677992e-03 -3.05666257e-03\n   2.06348734e-03  1.65001672e-03\
    \  4.86976948e-03]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x733b4686d190>
_custom_logger:
  desc: null
  value: 'False'
n_steps:
  desc: null
  value: 3936
gamma:
  desc: null
  value: 0.9885202328222382
gae_lambda:
  desc: null
  value: 0.9472233613269306
ent_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x733b7f1042b0>
batch_size:
  desc: null
  value: 123
n_epochs:
  desc: null
  value: 11
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x733b46947d30>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
